const familySelect=document.querySelector('#familySelect');const seedInput=document.querySelector('#seedInput');const runBtn=document.querySelector('#runBtn');const randomBtn=document.querySelector('#randomBtn');const comparisonGrid=document.querySelector('#comparisonGrid');const metricTable=document.querySelector('#metricTable');const uncertaintyPanel=document.querySelector('#uncertaintyPanel');const scenarioCharts=document.querySelector('#scenarioCharts');const familySummary=document.querySelector('#familySummary');const familyName=document.querySelector('#familyName');const stationCount=document.querySelector('#stationCount');const tripCount=document.querySelector('#tripCount');const budgetText=document.querySelector('#budgetText');const uncertaintyBadge=document.querySelector('#uncertaintyBadge');const toast=document.querySelector('#toast');

const lineColors=['#d84b4b','#3b79c9','#e7ad2f','#4d9f74','#8b61b8','#e27745'];
const familyMetrics={
  static:[['coverage_rate','覆盖率','pct'],['direct_trip_rate','直达率','pct'],['transfer_trip_rate','换乘率','pct'],['generalized_cost','广义出行成本','num'],['ride_distance','乘车距离','num'],['line_length','线路长度','num'],['design_compute_ms','设计耗时','ms']],
  infrastructure:[['feasible','可行','bool'],['coverage_rate','覆盖率','pct'],['direct_trip_rate','直达率','pct'],['generalized_cost','广义出行成本','num'],['construction_cost','建设成本','num'],['crossing_cost','跨障碍成本','num'],['barrier_crossings','障碍穿越','int'],['line_length','线路长度','num'],['design_compute_ms','设计耗时','ms']],
  uncertainty:[['nominal_coverage_rate','名义覆盖率','pct'],['oos_mean_coverage_rate','OOS平均覆盖率','pct'],['oos_worst_coverage_rate','OOS最差覆盖率','pct'],['oos_coverage_std','覆盖率波动','pct'],['nominal_generalized_cost','名义成本','num'],['oos_mean_generalized_cost','OOS平均成本','num'],['oos_worst_generalized_cost','OOS最差成本','num'],['oos_generalized_cost_std','成本波动','num'],['design_compute_ms','设计耗时','ms']]
};

function showToast(message){toast.textContent=message;toast.classList.add('show');clearTimeout(showToast.timer);showToast.timer=setTimeout(()=>toast.classList.remove('show'),1800)}
function fmt(value,type='num'){if(value===undefined||value===null)return'–';if(type==='pct')return`${(Number(value)*100).toFixed(1)}%`;if(type==='ms')return`${Number(value).toFixed(3)} ms`;if(type==='bool')return value?'是':'否';if(type==='int')return String(Math.round(Number(value)));return Number(value).toFixed(2)}
function esc(value){return String(value).replace(/[&<>"']/g,ch=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[ch]))}
function point(node,w,h,pad=28){return{x:pad+(node.x/100)*(w-pad*2),y:h-pad-(node.y/100)*(h-pad*2)}}

function renderNetwork(svg,data,algo){const w=720,h=460;svg.setAttribute('viewBox',`0 0 ${w} ${h}`);const nodes=data.instance.nodes;const byId=new Map(nodes.map(n=>[n.id,n]));const positions=new Map(nodes.map(n=>[n.id,point(n,w,h)]));const flows=[...(data.instance.demand?.flows||[])].sort((a,b)=>b.trips-a.trips).slice(0,26);const maxFlow=Math.max(...flows.map(f=>f.trips),1);let html='';
  for(const f of flows){const a=positions.get(f.origin_id),b=positions.get(f.destination_id);if(!a||!b)continue;const opacity=.10+.30*(f.trips/maxFlow);const sw=.7+3.2*(f.trips/maxFlow);html+=`<line x1="${a.x}" y1="${a.y}" x2="${b.x}" y2="${b.y}" stroke="#777a7e" stroke-width="${sw}" opacity="${opacity}"/>`}
  for(const barrier of data.barriers||[]){const a=point({x:barrier.x1,y:barrier.y1},w,h),b=point({x:barrier.x2,y:barrier.y2},w,h);html+=`<line x1="${a.x}" y1="${a.y}" x2="${b.x}" y2="${b.y}" stroke="${barrier.forbidden?'#9e3f3f':'#55585c'}" stroke-width="8" opacity=".42" stroke-dasharray="10 7"/>`}
  (algo.lines||[]).forEach((line,idx)=>{const ids=line.station_ids||[];const pts=ids.map(id=>positions.get(id)).filter(Boolean);if(pts.length<2)return;const color=lineColors[idx%lineColors.length];for(let i=0;i<pts.length-1;i++)html+=`<line x1="${pts[i].x}" y1="${pts[i].y}" x2="${pts[i+1].x}" y2="${pts[i+1].y}" stroke="#fff" stroke-width="9" stroke-linecap="round"/><line x1="${pts[i].x}" y1="${pts[i].y}" x2="${pts[i+1].x}" y2="${pts[i+1].y}" stroke="${color}" stroke-width="5" stroke-linecap="round"/>`;if(line.loop&&pts.length>2){const a=pts[pts.length-1],b=pts[0];html+=`<line x1="${a.x}" y1="${a.y}" x2="${b.x}" y2="${b.y}" stroke="#fff" stroke-width="9"/><line x1="${a.x}" y1="${a.y}" x2="${b.x}" y2="${b.y}" stroke="${color}" stroke-width="5"/>`}});
  for(const n of nodes){const p=positions.get(n.id);html+=`<circle cx="${p.x}" cy="${p.y}" r="9" fill="#fbfaf5" stroke="#202225" stroke-width="2.5"/><text x="${p.x+12}" y="${p.y-10}" font-size="10" font-weight="700" fill="#46484b">${esc(n.id)}</text>`}
  svg.innerHTML=html;
}

function miniMetricEntries(data,algo){const m=algo.metrics;if(data.family.key==='infrastructure')return[['覆盖率',fmt(m.coverage_rate,'pct')],['建设成本',fmt(m.construction_cost)],['跨障碍',fmt(m.barrier_crossings,'int')],['线路长度',fmt(m.line_length)]];if(data.family.key==='uncertainty')return[['名义覆盖',fmt(m.nominal_coverage_rate,'pct')],['OOS平均',fmt(m.oos_mean_coverage_rate,'pct')],['OOS最差',fmt(m.oos_worst_coverage_rate,'pct')],['OOS成本',fmt(m.oos_mean_generalized_cost)]];return[['覆盖率',fmt(m.coverage_rate,'pct')],['直达率',fmt(m.direct_trip_rate,'pct')],['广义成本',fmt(m.generalized_cost)],['线路长度',fmt(m.line_length)]]}

function renderPanels(data){comparisonGrid.innerHTML='';for(const algo of data.algorithms){const panel=document.createElement('article');panel.className='algorithm-panel';const meta=algo.metadata;panel.innerHTML=`<div class="algorithm-head"><div><div class="section-label">ALGORITHM</div><h2>${esc(meta.name||meta.id)}</h2><p>${esc(meta.description||'')}</p></div><span class="algo-id">${esc(meta.id)}</span></div><div class="network-stage"><svg aria-label="${esc(meta.name||meta.id)} 线路方案"></svg><div class="network-legend"><span>灰：OD</span><span>彩色：线路</span>${data.barriers?.length?'<span>虚线：障碍</span>':''}</div></div><div class="mini-metrics">${miniMetricEntries(data,algo).map(([k,v])=>`<div><span>${k}</span><strong>${v}</strong></div>`).join('')}</div>`;comparisonGrid.appendChild(panel);renderNetwork(panel.querySelector('svg'),data,algo)}}

function renderTable(data){const defs=familyMetrics[data.family.key]||[];metricTable.innerHTML=`<thead><tr><th>算法</th>${defs.map(([,label])=>`<th>${label}</th>`).join('')}</tr></thead><tbody>${data.algorithms.map(algo=>`<tr><td><strong>${esc(algo.metadata.name||algo.metadata.id)}</strong><br><small>${esc(algo.metadata.id)}</small></td>${defs.map(([key,,type])=>`<td>${fmt(algo.metrics[key],type)}</td>`).join('')}</tr>`).join('')}</tbody>`}

function renderScenarioChart(container,algo){const rows=algo.scenarios||[];const w=620,h=170,pad=24;const costs=rows.map(r=>r.generalized_cost);const covers=rows.map(r=>r.coverage_rate);const minC=Math.min(...costs,0),maxC=Math.max(...costs,1);const x=i=>pad+(i/(Math.max(rows.length-1,1)))*(w-pad*2);const yCoverage=v=>h-pad-v*(h-pad*2);const yCost=v=>h-pad-((v-minC)/(Math.max(maxC-minC,.0001)))*(h-pad*2);let paths='';for(let i=0;i<rows.length;i++){paths+=`<circle cx="${x(i)}" cy="${yCoverage(covers[i])}" r="4" fill="#3b79c9"/><circle cx="${x(i)}" cy="${yCost(costs[i])}" r="3" fill="#d84b4b" opacity=".7"/>`;}container.innerHTML=`<h3>${esc(algo.metadata.name||algo.metadata.id)}</h3><svg viewBox="0 0 ${w} ${h}" role="img" aria-label="隐藏需求场景表现"><line x1="${pad}" y1="${h-pad}" x2="${w-pad}" y2="${h-pad}" stroke="#d2cec4"/>${paths}</svg><div class="scenario-foot">蓝点：覆盖率（0–100%） · 红点：广义成本（按本算法场景范围缩放） · 共 ${rows.length} 个冻结未来</div>`}
function renderScenarios(data){const show=data.family.key==='uncertainty';uncertaintyPanel.hidden=!show;uncertaintyBadge.hidden=!show;scenarioCharts.innerHTML='';if(!show)return;for(const algo of data.algorithms){const card=document.createElement('div');card.className='scenario-card';scenarioCharts.appendChild(card);renderScenarioChart(card,algo)}}

function renderMeta(data){familySummary.textContent=data.family.summary;familyName.textContent=data.family.name;stationCount.textContent=data.instance.nodes.length;tripCount.textContent=Number(data.instance.demand.total_trips).toFixed(0);const b=data.instance.budget;budgetText.textContent=b?`${b.max_lines} 线 · 每线 ≤ ${b.max_stations_per_line} 站`:'–';document.title=`${data.family.name} · Mini Metro AI Lab`}

async function run(){const family=familySelect.value;const seed=Math.max(0,Math.min(2147483647,Number(seedInput.value)||0));seedInput.value=seed;comparisonGrid.innerHTML='<div class="loading">正在用同一组条件计算两种算法…</div>';runBtn.disabled=true;try{const res=await fetch(`/api/research/snapshot?family=${encodeURIComponent(family)}&seed=${seed}`,{cache:'no-store'});const data=await res.json();if(!res.ok)throw new Error(data.error||`HTTP ${res.status}`);renderMeta(data);renderPanels(data);renderTable(data);renderScenarios(data);history.replaceState(null,'',`/research.html?family=${encodeURIComponent(family)}&seed=${seed}`)}catch(err){comparisonGrid.innerHTML=`<div class="error">研究视图计算失败：${esc(err.message||err)}</div>`;showToast('计算失败')}finally{runBtn.disabled=false}}

const params=new URLSearchParams(location.search);if(params.has('family')&&['static','infrastructure','uncertainty'].includes(params.get('family')))familySelect.value=params.get('family');if(params.has('seed'))seedInput.value=params.get('seed');runBtn.addEventListener('click',run);familySelect.addEventListener('change',run);seedInput.addEventListener('keydown',e=>{if(e.key==='Enter')run()});randomBtn.addEventListener('click',()=>{seedInput.value=Math.floor(Math.random()*2147483647);run()});run();